[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
collector = { path = "../collector" }
models = { path = "../models" }
analyzer = { path = "../analyzer" }
parser = { path = "../parser" }
anyhow = "1.0"
# 워크스페이스 내 모든 크레이트와 버전을 일치시킵니다.
windows = { version = "0.52.0", features = ["Win32_Storage_FileSystem", "Win32_Foundation", "Win32_System_IO", "Win32_Security"] }
windows-core = "0.52.0"
chrono = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0"
rayon = "1.10"